import { Geist, Geist_Mono} from "next/font/google";
import { poppins, urbanist } from "./fonts/fonts";
import "./globals.css";
import { Navbar } from "./Componnents/Layouts/navbar/navbar";
import Footer from "./Componnents/Layouts/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={` ${poppins}, ${urbanist}, bg-slate-50
        
        
        dark:bg-slate-900 antialiased`}
      >
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
