import { Geist, Geist_Mono} from "next/font/google";
import { poppins, urbanist } from "./fonts/fonts";
import "./globals.css";

import { CartProvider } from "./Context/CartContex";
import { AuthProvider } from "./Context/AuthContext";
import { Footer } from "./componnents/layouts/Footer";
import { Navbar } from "./componnents/layouts/navbar/navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={` ${poppins}, ${urbanist}, bg-slate-50
        
        
        dark:bg-slate-900 antialiased`}

      >
        <AuthProvider>
        <CartProvider>
        <Navbar />
        {children}
        <Footer />
        </CartProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
